# Usar imagem oficial do Node.js
FROM node:20

# Definir diretório de trabalho
WORKDIR /app

# Copiar arquivos do frontend
COPY package.json package-lock.json ./
RUN npm install

# Copiar todo o código do frontend
COPY . .

# Expor a porta do frontend
EXPOSE 3000

# Comando para rodar o frontend em modo de desenvolvimento
CMD ["npm", "run", "dev"]
