version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      SQL_USER: admin
      SQL_PASSWORD: tLAcn7L2R32IRjfLM8NOssH5QVKCBjWJ
      SQL_DATABASE: tweet_db_av5w
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
