# Generated by Django 5.1.6 on 2025-02-12 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitterClone", "0002_remove_usuario_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="retweet_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="retweets",
                to="twitterClone.tweet",
            ),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="answer_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="twitterClone.tweet",
            ),
        ),
    ]
